/// Flutter icons Icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppCustomIcons {
  AppCustomIcons._();

  static const _kFontFam = 'Icons';
  static const String? _kFontPkg = null;

  static const IconData compass = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
